name       : liburcu
version    : 0.9.3
release    : 1
source     :
    - http://www.lttng.org/files/urcu/userspace-rcu-0.9.3.tar.bz2 : 1bce32e6a6c967fef6d37adaadf33df19878d69673f9ef9d3f2470e0c6ed4006
license    : LGPL-2.1
component  : programming.library
summary    : Userspace RCU (read-copy-update) library is a data synchronization library that provides read-side access which scales linearly with the number of cores.
description: |
    Userspace RCU (read-copy-update) library is a data synchronization library that provides read-side access which scales linearly with the number of cores.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install