name       : liburcu
version    : 0.13.0
release    : 2
source     :
    - https://lttng.org/files/urcu/userspace-rcu-0.13.0.tar.bz2 : cbb20dbe1a892c2a4d8898bac4316176e585392693d498766ccbbc68cf20ba20
homepage   : https://liburcu.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Userspace RCU Implementation
description: |
    liburcu is a userspace RCU (read-copy-update) library. This data synchronization library provides read-side access which scales linearly with the number of cores.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
